SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `Store` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;

CREATE TABLE IF NOT EXISTS `Store`.`Clientes` (
	`idClientes` INT(11) NOT NULL AUTO_INCREMENT,
	`Nome` VARCHAR(50) NULL DEFAULT NULL,
	`Telefone` INT(10) NULL DEFAULT NULL,
	`Celular` VARCHAR(11) NULL DEFAULT NULL,
	`Email` VARCHAR(100) NULL DEFAULT NULL,
	PRIMARY KEY (`idClientes`))
ENGINE = InnoDBde
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
